manifests/config.pp, manifests/init.pp, templates/20_workernode.config.erb
Enable cgroup in condor config. It is false by default. It does not setup cgroup for the machine.
Added DETECTED_CPU in WN template
=> enable cgroup

manifests/config/security.pp, templates/10_security.config.erb
The CERTIFICATE_MAPFILE is a "unified mapfile" (htcondor documentation term) used for all authentication
methods. 
It is not at all specific to Kerberos alone, but also treats SSL, FS etc.
=> htcondor::security Pull CERTIFICATE_MAPFILE out of krb-auth dependency.

manifests/config.pp, manifests/config/sharedport.pp, manifests/init.pp, manifests/params.pp, templates/42_shared_port.config.erb
Extremely useful in firewalled environments, off by default.
=> htcondor::sharedport: Add configuration for condor_shared_port daemon.

manifests/repositories.pp
The old baseurl string produced output like "http://research.cs.wisc.edu/htcondor/yum/stable/rhel7.3.1611". This URL does not exist.
=> Fix baseurl for yum repositories

manifests/config.pp, manifests/init.pp, manifests/params.pp
The notification does not play well with monitoring
such as the one provided by foreman,
since the machine will always be shown as "performed changes",
since puppet produced output.
This change allows to turn it off, but still leaves it on by default.
=> Allow to turn off debug notification.

templates/20_workernode.config.erb
This is not an expression, so the additional quotes are interpreted
as actual part of the path.
Sorry, my fault!
=> Remove bad quotes from MOUNT_UNDER_SCRATCH variable.

README.md, manifests/config/worker.pp, manifests/init.pp, manifests/params.pp, templates/20_workernode.config.erb
This allows to pass on environment seen by the
user's jobs, and also e.g. by the executed singularity
container.
It is especially helpful with singularity, since HTCondor does not (yet) take care of passing an appropriate home-directory to the container instance.
=> Add starter environment configuration

manifests/init.pp, manifests/params.pp, manifests/repositories.pp
By default the GPG signature of packages installed from the HTCondor stable and development repositories is checked now.
=> Add parameters gpgcheck and gpgkey

manifests/config/sharedport.pp, manifests/params.pp, templates/27_shared_port.config.erb, templates/30_highavailability.config.erb, templates/42_shared_port.config.erb
This patch allows that the had and replication daemons (for central manager HA) use the shared port daemon.
=> Central manager HA with shared port

manifests/config/worker.pp, manifests/init.pp, manifests/params.pp, metadata.json
Can be enabled / disabled with manage_selinux flag, default on (since SELinux is default on on all supported OS of this module). 
This requires `puppet/selinux` (from Voxpopuli) and fixes interactive jobs etc. if SELinux is activated,
since HTCondor installs SELinux rules for all that bound to the `condor_var_lib_t` type.
=> Setting of correct SELinux context for pool directory if we create it.

templates/20_workernode.config.erb
Since `MOUNT_UNDER_SCRATCH` can be problematic if payload jobs do not have write access, I've added two lines to the worker template to remove the config value if the parameter is set to an empty list (e.g. `htcondor::mount_under_scratch_dirs: []`)
=> Remove MOUNT_UNDER_SCRATCH if no folders are defined

manifests/config/worker.pp, manifests/params.pp
Importing two fixes from @afortiorama's fork:
- fixing issue #77 
- better default for `leave_job_in_queue`
=> Fixing permissions for worker healthcheck script (issue #77)

templates/50_singularity.config.erb
`SINGULARITY_IMAGE_EXPR` needs to be within double-quotes for HTCondor to parse it correctly
The current implementation causes the following error with condor `8.6.11`:
```
05/31/18 16:20:14 (pid:100974) Singularity support was requested but unable to determine the image to use.
05/31/18 16:20:14 (pid:100974) Singularity enabled but setup failed; failing job.
05/31/18 16:20:14 (pid:100974) Failed to start job, exiting
05/31/18 16:20:14 (pid:100974) ShutdownFast all jobs.
```
=> Fixing invalid SINGULARITY_IMAGE_EXPR by adding missing double-quotes

README.md, templates/50_singularity.config.erb
It's an expression, forcefully enclosing it in double quotes degrades it to a string. 
This PR reverts that, and rather fixes the example in the documentation, which already clarifies an expression can be specified. 
Fixes #91 .
=> Fixup SINGULARITY_IMAGE_EXPR

manifests/config/security.pp, manifests/init.pp, manifests/params.pp, templates/10_security.config.erb
This adds knobs for `queue_super_users` and `queue_super_user_may_impersonate` (which is a string that may be a regexp matching user names). 
fixes #97
=> Queue super users

README.md, examples/htcondor_remote_submit.yaml, manifests/config.pp, manifests/config/remote_submit.pp, manifests/init.pp, manifests/params.pp, manifests/service.pp
This PR defines a new type of node : **remote_submit**
The idea comes from this [DESY talk](https://agenda.hep.wisc.edu/event/1201/session/9/contribution/40/material/slides/0.pdf), slide 11: a remote submit allows you to:
* let your users login
* provide them a configured _condor_submit_ to submit jobs to a schedd, mentioned in conf (may be a personnal conf, _~/.condor/user_config_, see [this doc](https://htcondor-wiki.cs.wisc.edu/index.cgi/wiki?p=HowToLoadBalanceUsersToSubmitNodes))
* be able to get this host down (for software updates for example) seamlessly, so no downtime when a breach in the kernel has to be patched
* retrieve your files if you have a shared FS between schedd and remote_submit
So this PR implements a fourth type of node (after manager, scheduler,worker), called …
=> Add a "remote_submit" role

metadata.json
Set correct parsable ranges on module requirements to pass Travis tests
=> fix requirements range error for travis test

manifests/init.pp, manifests/params.pp, manifests/repositories.pp, metadata.json
This PR adds two features:
- Initial support for Debian and Ubuntu. Just adding the repositories is sufficient. We are using at least schedds on Ubuntu successfully. This adds `puppetlabs/apt` as a dependency. 
- Adapting to the new repository structure of HTCondor. 
HTCondor restructured their repositories with 8.8 from the old previous / stable / development to versioned subdirectories. This means updates are significantly less surprising as compared to the past workflow when `stable` contained `8.4` and was suddenly replaced by `8.6` over night. 
For backwards compatibility, the flag `versioned_repositories` is false by default, and the "old" repositories are still used. To accomodate the new URLs, `condor_major_version` (defaulting to `8.8` which is the first version in a versioned …
=> Add support for Debian repos and new versioned repo structure.

templates/20_workernode.config.erb, templates/condor_config.local.erb
If it is only set on the workernodes,
jobs will still be killed when the schedds are updated,
since they restart gracefully by default, killing
all shadows.
=> Move MASTER_NEW_BINARY_RESTART=PEACEFUL to condor_config.

.travis.yml
- removed older RVM versions ( < 2.3.X )
- added Puppet 5 & 6 to test matrix
=> Puppet 5 & Puppet 6 in CI

manifests/config/common.pp, manifests/init.pp, manifests/params.pp, templates/condor_config.local.erb
Used to define the period when HTCondor requeries DNS
e.g. to resolve permissions of hosts.
Important since HTCondor also caches NXDOMAIN.
HTCondor default is 8 hours + a random offset of up to 10m
to avoid pounding of DNS servers,
which we mimic with fqdn_rand in puppet.
=> Add dns_cache_refresh parameter.

manifests/config/scheduler.pp, manifests/init.pp, manifests/params.pp, templates/21_schedd.config.erb
Users listed in schedd_blocked_users will be disallowed
from submission and message provided via schedd_blocked_user_msg
will be shown.
Useful e.g. to temporarily block users to force them to contact
cluster admins.
=> Add schedd_blocked_users and block message.

manifests/config/worker.pp, manifests/init.pp, manifests/params.pp, templates/20_workernode.config.erb
These users are always allowed to run jobs,
even on nodes which fail the health check or
for which startjobs is false.
This allows admins to mask production machines
for tests and use them exclusively.
=> Allow to define start_always_users.

manifests/config/common.pp
Backing up the config.d files  leads to very unwanted behaviour.
Reason is that according to doc (https://htcondor.readthedocs.io/en/v8_8_5/admin-manual/introduction-to-configuration.html#ordered-evaluation-to-set-the-configuration) , all files within the config.d are parsed in a lexicographic order.
The issue therefore is : 
00_config_local.config
is lexicographically parsed before :
00_config_local.config.bak.123456
which is parsed before 
00_config_local.config.bak.456789
So : in case of any change inside the config_local.config files, and this happenned to us several times, the old configs actually do override the new configs, and things are not working as expected on condor_reconfig or condor_restart.
But worse : since the new .bak file is not managed, it is removed on subsequent …
=> make sure not to backup the main config file

manifests/config/security.pp, manifests/init.pp, manifests/params.pp, templates/10_security.config.erb
Very small change to make the USERS variable customizable in _/etc/condor/config.d/10_security.config_
The variable name may be modified if you don't fix it clear enough?
=> USERS customizable

manifests/repositories.pp
Reasoning: Upstream servers redirect to HTTPS anyways,
and if we hardcode HTTP, some cachers are broken
(notably, `aptcacher-ng` triggers a bad redirect).
Using HTTPS natively prevents such issues.
=> repositories: Switch to HTTPS URLs.

manifests/repositories.pp
@ccnifo @kreczko While this adapts to the apparently changed HTCondor repository layout (again — both yum and apt repos changed), I'd also like to ask your opinion on how to proceed on this. 
What this PR does: Adapt the `versioned_repos` case to use the new repo layout. 
* The new repo layout contains several 8.8 releases and many 8.9 releases, and new releases only seem to go there. 
* The non-`versioned_repos` contain the 8.6 series and older releases. 
* This PR drops the "intermediate" repository structure which contains most 8.8 releases (apart from newer ones) and some 8.9 releases (apart from newer ones). 
My thoughts when implementing things this way were:
* Supporting all three structures does not seem reasonable.
* The new layout contains what new users will want to use, and …
=> Adapt to changed HTCondor repository structure

manifests/repositories.pp
This was accidentally removed in 5a754e8fc612bcb64fae75d8e2110e8705012afb (by me :sob: )
since it is not used in the repository name anymore, but it is still used in the `apt::source` resource. 
Note this worked nevertheless, since this is a fallback used in `apt::source`. It still seems more concise to pass in a known-good value here for the HTCondor repository layout.
=> repositories: Add back missing distro_code variable.

manifests/init.pp, manifests/params.pp, manifests/repositories.pp
This matches the support we have for `gpgkey` which affects the RPM repositories. 
Since HTCondor upstream has (again) changed repository structure and is now also using different signing keys for each variant:
https://research.cs.wisc.edu/htcondor/repo/keys/
it seems reasonable to be more flexible here, to allow consumers of the module to react to upstream's changes faster and potentially also to simplify rolling out their own repository mirrors. 
For reference, I am using code as follows locally, to support the current `9.0`, `9.1` and previous versions:
```
if ($facts['os']['family'] == 'Debian') {
if (versioncmp($htcondor_version, '9.0') == -1) {
$_apt_key_source = 'https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-Release.gpg.key'
$_apt_key_id = …
```
=> Add knobs to overwrite `apt_key_id` and `apt_key_source`
